server:
  port: 8083

spring:
  application:
    name: notification-service
  
  datasource:
    url: jdbc:postgresql://localhost:5433/sql7
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:/}

logging:
  level:
    com.freelance.lifecycle: DEBUG
    org.springframework.web: DEBUG
    org.springframework.amqp: DEBUG
