server:
  port: 8080

spring:
  application:
    name: application-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/sql4
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  level:
    com.freelance.lifecycle: DEBUG
    org.springframework.web: DEBUG
