server:
  port: 8000

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      routes:
        # Application Service Route
        - id: application-service
          uri: http://application-service:8080
          predicates:
            - Path=/api/v1/applications/**
          filters:
            - StripPrefix=2
        
        # Notification Service Route
        - id: notification-service
          uri: http://notification-service:8083
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - StripPrefix=2
        
        # Project Service Route (for future implementation)
        - id: project-service
          uri: http://project-service:8081
          predicates:
            - Path=/api/v1/projects/**
          filters:
            - StripPrefix=2
        
        # User Service Route (for future implementation)
        - id: user-service
          uri: http://user-service:8082
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2
      
      # Global CORS configuration
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

# Logging configuration
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG
